theme: jekyll-theme-minimal
title: Paid Parental Leave at US and Canadian Universities
description: A dataset of parental leave policies. Equal contributions by Allison C. Morgan, Samuel F. Way, Mirta Galesic, Daniel B. Larremore, and Aaron Clauset. 
show_downloads: true
